[package]
name = "guesswho"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.32"
rayon = "1.10"
wgpu = "22.1"
pollster = "0.4"
bytemuck = { version = "1.14", features = ["derive"] }
